### ISSUE TITLE
high quality and high definition

### ISSUE THREAD

**Issue by mmlingyu** [facebookresearch/vfusion3d#6]
The --render_size parameter is set to 256 or even 128. What kind of settings can generate a model with high quality and high definition? Is there a corresponding GPU configuration reference?

**Comment by mmlingyu** [comment]
why the hugging face online demo，the obj model have no font view ？

**Comment by JunlinHan** [comment]
Do you mean mesh results? For better mesh results, you can try increasing --mesh_size.

The Hf demo should have a front view, but the UI makes it difficult to navigate to that part. Try downloading the OBJ file and using other display tools.
