### ISSUE TITLE
Releasing synthetic dataset

### ISSUE THREAD

**Issue by hieu1999210** [facebookresearch/vfusion3d#9]
Thank you for such great work.

Are you going to release any parts of the synthetic dataset? Either the caption or images?
Thanks

**Comment by JunlinHan** [comment]
Hello, thanks a lot for your kind words.

likely no. we don't have plans for releasing them. 

For captions, you might try LAION, which should provide enough object-centric captions.

**Comment by hieu1999210** [comment]
thanks
